# Generated by Django 2.1.8 on 2019-05-22 09:13

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Client name', max_length=256, unique=True)),
                ('contact_name', models.CharField(blank=True, help_text='Contact name', max_length=256, null=True)),
                ('email', models.EmailField(help_text='Email address', max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='Phone number', max_length=128, region=None)),
                ('street_name', models.CharField(blank=True, help_text='Street name', max_length=256, null=True)),
                ('suburb', models.CharField(blank=True, help_text='Street name', max_length=256, null=True)),
                ('postcode', models.CharField(blank=True, help_text='Post code', max_length=16, null=True)),
                ('state', models.CharField(blank=True, choices=[('AL', 'AL'), ('AK', 'AK'), ('AZ', 'AZ'), ('AR', 'AR'), ('CA', 'CA'), ('CO', 'CO'), ('CT', 'CT'), ('DE', 'DE'), ('DC', 'DC'), ('FL', 'FL'), ('GA', 'GA'), ('HI', 'HI'), ('ID', 'ID'), ('IL', 'IL'), ('IN', 'IN'), ('IA', 'IA'), ('KS', 'KS'), ('KY', 'KY'), ('LA', 'LA'), ('ME', 'ME'), ('MD', 'MD'), ('MA', 'MA'), ('MI', 'MI'), ('MN', 'MN'), ('MS', 'MS'), ('MO', 'MO'), ('MT', 'MT'), ('NE', 'NE'), ('NV', 'NV'), ('NH', 'NH'), ('NJ', 'NJ'), ('NM', 'NM'), ('NY', 'NY'), ('NC', 'NC'), ('ND', 'ND'), ('OH', 'OH'), ('OK', 'OK'), ('OR', 'OR'), ('PA', 'PA'), ('RI', 'RI'), ('SC', 'SC'), ('SD', 'SD'), ('TN', 'TN'), ('TX', 'TX'), ('UT', 'UT'), ('VT', 'VT'), ('VA', 'VA'), ('WA', 'WA'), ('WV', 'WV'), ('WI', 'WI'), ('WY', 'WY')], help_text='State code', max_length=2, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['name'], name='python_test_name_7f7fd1_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['email'], name='python_test_email_bec9da_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['suburb'], name='python_test_suburb_4ea38b_idx'),
        ),
    ]
